#ifndef _EDITUSERPAGE_H_
#define _EDITUSERPAGE_H_

#include "ui.h"

#define IDC_STATIC_EDITUSER_USER			IDD_DIALOG_EDITUSER+1
#define IDC_STATIC_EDITUSER_PASSWD			IDD_DIALOG_EDITUSER+2
#define IDC_STATIC_EDITUSER_SURE			IDD_DIALOG_EDITUSER+3

#define IDC_EDIT_EDITUSER_USER				IDD_DIALOG_EDITUSER+4
#define IDC_EDIT_EDITUSER_PASSWD			IDD_DIALOG_EDITUSER+5
#define IDC_EDIT_EDITUSER_SURE				IDD_DIALOG_EDITUSER+6

#define IDC_STATIC_EDITUSER_TEMPLET			IDD_DIALOG_EDITUSER+7
#define IDC_COMBO_EDITUSER_TEMPLET			IDD_DIALOG_EDITUSER+8
#define IDC_BUTTON_EDITUSER_SELECT			IDD_DIALOG_EDITUSER+9

#define IDC_STATIC_EDITUSER_LOCAL			IDD_DIALOG_EDITUSER+10

#define IDC_CHECK_EDITUSER_LOCALYUNTAI		IDD_DIALOG_EDITUSER+11
#define IDC_CHECK_EDITUSER_LOCALRECORD		IDD_DIALOG_EDITUSER+12
#define IDC_CHECK_EDITUSER_LOCALPLAY		IDD_DIALOG_EDITUSER+13
#define IDC_CHECK_EDITUSER_LOCALSET			IDD_DIALOG_EDITUSER+14
#define IDC_CHECK_EDITUSER_LOCALLOG			IDD_DIALOG_EDITUSER+15
#define IDC_CHECK_EDITUSER_LOCALTOOL		IDD_DIALOG_EDITUSER+16

#define IDC_STATIC_EDITUSER_REMOTE			IDD_DIALOG_EDITUSER+17

#define IDC_CHECK_EDITUSER_REMOTEYUNTAI		IDD_DIALOG_EDITUSER+18
#define IDC_CHECK_EDITUSER_REMOTERECORD		IDD_DIALOG_EDITUSER+19
#define IDC_CHECK_EDITUSER_REMOTEPLAY		IDD_DIALOG_EDITUSER+20
#define IDC_CHECK_EDITUSER_REMOTESET		IDD_DIALOG_EDITUSER+21
#define IDC_CHECK_EDITUSER_REMOTELOG		IDD_DIALOG_EDITUSER+22
#define IDC_CHECK_EDITUSER_REMOTETOOL		IDD_DIALOG_EDITUSER+23
#define IDC_CHECK_EDITUSER_REMOTEPREVIEW	IDD_DIALOG_EDITUSER+24
#define IDC_CHECK_EDITUSER_REMOTEALARM		IDD_DIALOG_EDITUSER+25

#define IDC_STATIC_EDITUSER_PHYSICALADDR	IDD_DIALOG_EDITUSER+26
#define IDC_EDIT_EDITUSER_PHYSICALADDR		IDD_DIALOG_EDITUSER+27

#define IDC_BUTTON_EDITUSER_OK				IDD_DIALOG_EDITUSER+28
#define IDC_BUTTON_EDITUSER_CANCEL			IDD_DIALOG_EDITUSER+29

BOOL CreateEdituserPage();
BOOL ShowEdituserPage();

#endif
