#ifndef _EXCEPTIONPAGE_H_
#define _EXCEPTIONPAGE_H_

#include "ui.h"

#define IDC_STATIC_EXCEPTION_TYPE			IDD_DIALOG_EXCEPTION+1
#define IDC_STATIC_EXCEPTION_DISPLAY		IDD_DIALOG_EXCEPTION+2
#define IDC_STATIC_EXCEPTION_SOUNDALARM		IDD_DIALOG_EXCEPTION+3
#define IDC_STATIC_EXCEPTION_CENTER			IDD_DIALOG_EXCEPTION+4
#define IDC_STATIC_EXCEPTION_OUT			IDD_DIALOG_EXCEPTION+5

#define IDC_STATIC_EXCEPTION_OUT1			IDD_DIALOG_EXCEPTION+6
#define IDC_STATIC_EXCEPTION_OUT2			IDD_DIALOG_EXCEPTION+7
#define IDC_STATIC_EXCEPTION_OUT3			IDD_DIALOG_EXCEPTION+8
#define IDC_STATIC_EXCEPTION_OUT4			IDD_DIALOG_EXCEPTION+9

#define IDC_COMBO_EXCEPTION_TYPE			IDD_DIALOG_EXCEPTION+10
#define IDC_CHECK_EXCEPTION_DISPLAY			IDD_DIALOG_EXCEPTION+11
#define IDC_CHECK_EXCEPTION_SOUNDALARM		IDD_DIALOG_EXCEPTION+12
#define IDC_CHECK_EXCEPTION_CENTER			IDD_DIALOG_EXCEPTION+13
#define IDC_CHECK_EXCEPTION_OUT				IDD_DIALOG_EXCEPTION+14

#define IDC_CHECK_EXCEPTION_OUT1			IDD_DIALOG_EXCEPTION+15
#define IDC_CHECK_EXCEPTION_OUT2			IDD_DIALOG_EXCEPTION+16
#define IDC_CHECK_EXCEPTION_OUT3			IDD_DIALOG_EXCEPTION+17
#define IDC_CHECK_EXCEPTION_OUT4			IDD_DIALOG_EXCEPTION+18

#define IDC_BUTTON_EXCEPTION_OK				IDD_DIALOG_EXCEPTION+19
#define IDC_BUTTON_EXCEPTION_CANCEL			IDD_DIALOG_EXCEPTION+20

BOOL CreateExceptionPage();
BOOL ShowExceptionPage();

#endif
