#ifndef _IMAGESETPAGE_H_
#define _IMAGESETPAGE_H_

#include "ui.h"

#define IDC_STATIC_IMAGESET_CHNINDEX					IDD_DIALOG_IMAGESET+1
#define IDC_COMBO_IMAGESET_CHNINDEX						IDD_DIALOG_IMAGESET+2

#define IDC_STATIC_IMAGESET_CHNNAME						IDD_DIALOG_IMAGESET+3
#define IDC_EDIT_IMAGESET_CHNNAME						IDD_DIALOG_IMAGESET+4

#define IDC_STATIC_IMAGESET_CHNNAMEDISPLAY				IDD_DIALOG_IMAGESET+5
#define IDC_CHECK_IMAGESET_CHNNAMEDISPLAY				IDD_DIALOG_IMAGESET+6
#define IDC_BUTTON_IMAGESET_CHNNAMEDISPLAY				IDD_DIALOG_IMAGESET+7

#define IDC_STATIC_IMAGESET_BRIGHTNESS					IDD_DIALOG_IMAGESET+8
#define IDC_BUTTON_IMAGESET_BRIGHTNESS					IDD_DIALOG_IMAGESET+9

#define IDC_STATIC_IMAGESET_CONTRAST					IDD_DIALOG_IMAGESET+10
#define IDC_BUTTON_IMAGESET_CONTRAST					IDD_DIALOG_IMAGESET+11

#define IDC_STATIC_IMAGESET_HUE							IDD_DIALOG_IMAGESET+12
#define IDC_BUTTON_IMAGESET_HUE							IDD_DIALOG_IMAGESET+13

#define IDC_STATIC_IMAGESET_SATURATION					IDD_DIALOG_IMAGESET+14
#define IDC_BUTTON_IMAGESET_SATURATION					IDD_DIALOG_IMAGESET+15

#define IDC_STATIC_IMAGESET_SHOWTIME					IDD_DIALOG_IMAGESET+16
#define IDC_CHECK_IMAGESET_SHOWTIME						IDD_DIALOG_IMAGESET+17
#define IDC_BUTTON_IMAGESET_SHOWTIME					IDD_DIALOG_IMAGESET+18

#define IDC_STATIC_IMAGESET_ENVELOP						IDD_DIALOG_IMAGESET+19
#define IDC_CHECK_IMAGESET_ENVELOP						IDD_DIALOG_IMAGESET+20
#define IDC_BUTTON_IMAGESET_ENVELOPAREA					IDD_DIALOG_IMAGESET+21

#define IDC_STATIC_IMAGESET_SHELTERALARM				IDD_DIALOG_IMAGESET+22
#define IDC_COMBO_IMAGESET_SHELTERALARM					IDD_DIALOG_IMAGESET+23
#define IDC_BUTTON_IMAGESET_SHELTERALARMSET				IDD_DIALOG_IMAGESET+24

#define IDC_STATIC_IMAGESET_VIDEOLOSEALARM				IDD_DIALOG_IMAGESET+25
#define IDC_COMBO_IMAGESET_VIDEOLOSEALARM				IDD_DIALOG_IMAGESET+26
#define IDC_BUTTON_IMAGESET_VIDEOLOSEALARMSET			IDD_DIALOG_IMAGESET+27

#define IDC_STATIC_IMAGESET_MOTIONDETECTALARM			IDD_DIALOG_IMAGESET+28
#define IDC_COMBO_IMAGESET_MOTIONDETECTALARM			IDD_DIALOG_IMAGESET+29
#define IDC_BUTTON_IMAGESET_MOTIONDETECTALARMSET		IDD_DIALOG_IMAGESET+30
#define IDC_BUTTON_IMAGESET_MOTIONDETECTALARMAREA		IDD_DIALOG_IMAGESET+31
#define IDC_BUTTON_IMAGESET_MOTIONDETECTALARMDISPOSE	IDD_DIALOG_IMAGESET+32

#define IDC_STATIC_IMAGESET_COPY						IDD_DIALOG_IMAGESET+33
#define IDC_COMBO_IMAGESET_COPY							IDD_DIALOG_IMAGESET+34
#define IDC_BUTTON_IMAGESET_COPY						IDD_DIALOG_IMAGESET+35

#define IDC_BUTTON_IMAGESET_OK							IDD_DIALOG_IMAGESET+36
#define IDC_BUTTON_IMAGESET_CANCEL						IDD_DIALOG_IMAGESET+37

#define IDC_INPUTBOX_IMAGESET_DENO						IDD_DIALOG_IMAGESET+38

BOOL CreateImagesetPage();
BOOL ShowImagesetPage();

#endif
