#ifndef _LOGPAGE_H_
#define _LOGPAGE_H_

#include "ui.h"

#define IDC_STATIC_LOG_QUERYWAY			IDD_DIALOG_LOG+1
#define IDC_STATIC_LOG_MAINTYPE			IDD_DIALOG_LOG+2
#define IDC_STATIC_LOG_SECONDTYPE		IDD_DIALOG_LOG+3
#define IDC_STATIC_LOG_STARTTIME		IDD_DIALOG_LOG+4
#define IDC_STATIC_LOG_ENDTIME			IDD_DIALOG_LOG+5

#define IDC_COMBO_LOG_QUERYWAY			IDD_DIALOG_LOG+6
#define IDC_COMBO_LOG_MAINTYPE			IDD_DIALOG_LOG+7
#define IDC_COMBO_LOG_SECONDTYPE		IDD_DIALOG_LOG+8
#define IDC_EDIT_LOG_STARTDATE			IDD_DIALOG_LOG+9
#define IDC_EDIT_LOG_STARTTIME			IDD_DIALOG_LOG+10
#define IDC_EDIT_LOG_ENDDATE			IDD_DIALOG_LOG+11
#define IDC_EDIT_LOG_ENDTIME			IDD_DIALOG_LOG+12

#define IDC_BUTTON_LOG_QUERY			IDD_DIALOG_LOG+13

#define IDC_STATIC_LOG_INDEX			IDD_DIALOG_LOG+14
#define IDC_STATIC_LOG_RECORDTIME		IDD_DIALOG_LOG+15
#define IDC_STATIC_LOG_RECORDMAINTYPE	IDD_DIALOG_LOG+16
#define IDC_STATIC_LOG_RECORDSECONDTYPE	IDD_DIALOG_LOG+17

#define IDC_LIST_LOG_INFO				IDD_DIALOG_LOG+18

#define IDC_BUTTON_LOG_PREPAGE			IDD_DIALOG_LOG+19
#define IDC_BUTTON_LOG_NEXTPAGE			IDD_DIALOG_LOG+20

#define IDC_STATIC_LOG_SELECTPAGE		IDD_DIALOG_LOG+21
#define IDC_EDIT_LOG_SELECTPAGE			IDD_DIALOG_LOG+22

#define IDC_STATIC_LOG_COMPART			IDD_DIALOG_LOG+23
#define IDC_STATIC_LOG_TOTALPAGE		IDD_DIALOG_LOG+24

#define IDC_BUTTON_LOG_MORE				IDD_DIALOG_LOG+25
#define IDC_BUTTON_LOG_BACK				IDD_DIALOG_LOG+26

#define IDC_DATETIME_LOG_STARTTIME            IDD_DIALOG_LOG+27
#define IDC_DATETIME_LOG_ENDTIME                IDD_DIALOG_LOG+28

#define IDC_BUTTON_LOG_GOTOPAGE                 IDD_DIALOG_LOG+29

BOOL CreateLogPage();
BOOL ShowLogPage();

void OnLogQueryWay(s32 param);
void OnLogMainType(s32 param);
void OnLogSearch(s32 param);
void OnLogPre(s32 param);
void OnLogNext(s32 param);
void OnLogCurPage(s32 param);
void OnLogMore(s32 param);
void OnLogBack(s32 param);

#endif
