#ifndef _NETWORKPAGE_H_
#define _NETWORKPAGE_H_

#include "ui.h"

#define IDC_STATIC_NETWORK_MAC			IDD_DIALOG_NETWORK+1
#define IDC_STATIC_NETWORK_IP			IDD_DIALOG_NETWORK+2
#define IDC_STATIC_NETWORK_SUBNET		IDD_DIALOG_NETWORK+3
#define IDC_STATIC_NETWORK_DNS			IDD_DIALOG_NETWORK+4
#define IDC_STATIC_NETWORK_SERVIP		IDD_DIALOG_NETWORK+5
#define IDC_STATIC_NETWORK_HTTPPORT		IDD_DIALOG_NETWORK+6

#define IDC_EDIT_NETWORK_MAC			IDD_DIALOG_NETWORK+7
#define IDC_EDIT_NETWORK_IP				IDD_DIALOG_NETWORK+8
#define IDC_EDIT_NETWORK_SUBNET			IDD_DIALOG_NETWORK+9
#define IDC_EDIT_NETWORK_DNS			IDD_DIALOG_NETWORK+10
#define IDC_EDIT_NETWORK_SERVIP			IDD_DIALOG_NETWORK+11
#define IDC_EDIT_NETWORK_HTTPPORT		IDD_DIALOG_NETWORK+12

#define IDC_STATIC_NETWORK_PORT			IDD_DIALOG_NETWORK+13
#define IDC_STATIC_NETWORK_GATEWAY		IDD_DIALOG_NETWORK+14
#define IDC_STATIC_NETWORK_MULTICAST	IDD_DIALOG_NETWORK+15
#define IDC_STATIC_NETWORK_SERVPORT		IDD_DIALOG_NETWORK+16

#define IDC_EDIT_NETWORK_PORT			IDD_DIALOG_NETWORK+17
#define IDC_EDIT_NETWORK_GATEWAY		IDD_DIALOG_NETWORK+18
#define IDC_EDIT_NETWORK_MULTICAST		IDD_DIALOG_NETWORK+19
#define IDC_EDIT_NETWORK_SERVPORT		IDD_DIALOG_NETWORK+20

#define IDC_STATIC_NETWORK_PPPOE		IDD_DIALOG_NETWORK+21
#define IDC_CHECK_NETWORK_PPPOEENABLE	IDD_DIALOG_NETWORK+22

#define IDC_STATIC_NETWORK_PPPOEUSER	IDD_DIALOG_NETWORK+23
#define IDC_STATIC_NETWORK_PPPOEPASSWD	IDD_DIALOG_NETWORK+24
#define IDC_STATIC_NETWORK_PPPOEVERIFY	IDD_DIALOG_NETWORK+25

#define IDC_EDIT_NETWORK_PPPOEUSER		IDD_DIALOG_NETWORK+26
#define IDC_EDIT_NETWORK_PPPOEPASSWD	IDD_DIALOG_NETWORK+27
#define IDC_EDIT_NETWORK_PPPOEVERIFY	IDD_DIALOG_NETWORK+28

#define IDC_BUTTON_NETWORK_OK			IDD_DIALOG_NETWORK+29
#define IDC_BUTTON_NETWORK_CANCEL		IDD_DIALOG_NETWORK+30

BOOL CreateNetworkPage();
BOOL ShowNetworkPage();

#endif
