#ifndef _RESTARTPAGE_H_
#define _RESTARTPAGE_H_

#include "ui.h"

#define IDC_STATIC_RESTART_TEXT1		IDD_DIALOG_RESTART+1
#define IDC_STATIC_RESTART_TEXT2		IDD_DIALOG_RESTART+2

#define IDC_BUTTON_RESTART_OK			IDD_DIALOG_RESTART+3
#define IDC_BUTTON_RESTART_CANCEL		IDD_DIALOG_RESTART+4

BOOL CreateRestartPage();
BOOL ShowRestartPage();

#endif
