#ifndef _SYSDATETIMEPAGE_H_
#define _SYSDATETIMEPAGE_H_

#include "ui.h"

#define IDC_STATIC_SYSDATETIME_DATE		IDD_DIALOG_SYSDATETIME+1
#define IDC_STATIC_SYSDATETIME_TIME		IDD_DIALOG_SYSDATETIME+2  

#define IDC_DATETIME_SYSDATETIME_DATE			IDD_DIALOG_SYSDATETIME+3
#define IDC_DATETIME_SYSDATETIME_TIME		  IDD_DIALOG_SYSDATETIME+4

#define IDC_BUTTON_SYSDATETIME_OK		  IDD_DIALOG_SYSDATETIME+5
#define IDC_BUTTON_SYSDATETIME_CANCEL	IDD_DIALOG_SYSDATETIME+6
#define IDC_INPUTBOX_SYSDATETIME_DENO	IDD_DIALOG_SYSDATETIME+7

BOOL CreateSysDateTimePage();
BOOL ShowSysDateTimePage();

void OnSysDateTimeOK(s32 param);
void OnSysDateTimeCancel(s32 param);

#endif

