#ifndef _SYSTEMPAGE_H_
#define _SYSTEMPAGE_H_

#include "ui.h"

#define PIC_SYSTEM_TOOL			"data/pics/system/tool.png"
#define PIC_SYSTEM_LOG			"data/pics/system/log.png"
#define PIC_SYSTEM_USER			"data/pics/system/user.png"
#define PIC_SYSTEM_NETWORK		"data/pics/system/network.png"
#define PIC_SYSTEM_IMAGE		"data/pics/system/image.png"
#define PIC_SYSTEM_RECORD		"data/pics/system/record.png"
#define PIC_SYSTEM_YUNTAI		"data/pics/system/yuntai.png"
#define PIC_SYSTEM_ALARM		"data/pics/system/alarm.png"
#define PIC_SYSTEM_EXCEPTION	"data/pics/system/exception.png"

#define IDC_STATIC_SYSTEM_TOOL			IDD_DIALOG_SYSTEM+1
#define IDC_STATIC_SYSTEM_LOG			IDD_DIALOG_SYSTEM+2
#define IDC_STATIC_SYSTEM_USER			IDD_DIALOG_SYSTEM+3
#define IDC_STATIC_SYSTEM_NETWORK		IDD_DIALOG_SYSTEM+4
#define IDC_STATIC_SYSTEM_IMAGE			IDD_DIALOG_SYSTEM+5
#define IDC_STATIC_SYSTEM_RECORD		IDD_DIALOG_SYSTEM+6
#define IDC_STATIC_SYSTEM_YUNTAI		IDD_DIALOG_SYSTEM+7
#define IDC_STATIC_SYSTEM_ALARM			IDD_DIALOG_SYSTEM+8
#define IDC_STATIC_SYSTEM_EXCEPTION		IDD_DIALOG_SYSTEM+9
#define IDC_PICTURE_SYSTEM_TOOL			IDD_DIALOG_SYSTEM+10
#define IDC_PICTURE_SYSTEM_LOG			IDD_DIALOG_SYSTEM+11
#define IDC_PICTURE_SYSTEM_USER			IDD_DIALOG_SYSTEM+12
#define IDC_PICTURE_SYSTEM_NETWORK		IDD_DIALOG_SYSTEM+13
#define IDC_PICTURE_SYSTEM_IMAGE		IDD_DIALOG_SYSTEM+14
#define IDC_PICTURE_SYSTEM_RECORD		IDD_DIALOG_SYSTEM+15
#define IDC_PICTURE_SYSTEM_YUNTAI		IDD_DIALOG_SYSTEM+16
#define IDC_PICTURE_SYSTEM_ALARM		IDD_DIALOG_SYSTEM+17
#define IDC_PICTURE_SYSTEM_EXCEPTION	IDD_DIALOG_SYSTEM+18

BOOL CreateSystemPage();
BOOL ShowSystemPage();

#endif
