#ifndef _UPDATEPAGE_H_
#define _UPDATEPAGE_H_

#include "ui.h"

#define IDC_STATIC_UPDATE_WAY		IDD_DIALOG_UPDATE+1
#define IDC_STATIC_UPDATE_SERVIP	IDD_DIALOG_UPDATE+2

#define IDC_COMBO_UPDATE_WAY		IDD_DIALOG_UPDATE+3
#define IDC_EDIT_UPDATE_SERVIP		IDD_DIALOG_UPDATE+4

#define IDC_BUTTON_UPDATE_OK		IDD_DIALOG_UPDATE+5
#define IDC_BUTTON_UPDATE_CANCEL	IDD_DIALOG_UPDATE+6

BOOL CreateUpdatePage();
BOOL ShowUpdatePage();

#define IDC_STATIC_UPDATESUCC_TEXT	IDD_DIALOG_UPDATESUCC+1
#define IDC_BUTTON_UPDATESUCC_OK	IDD_DIALOG_UPDATESUCC+2	

BOOL CreateUpdateSuccPage();
BOOL ShowUpdateSuccPage();

#endif
