#ifndef _USERMANAGEPAGE_H_
#define _USERMANAGEPAGE_H_

#include "ui.h"

#define IDC_STATIC_USERMANAGE_INDEX			IDD_DIALOG_USERMANAGE+1
#define IDC_STATIC_USERMANAGE_USER			IDD_DIALOG_USERMANAGE+2

#define IDC_LIST_USERMANAGE_USERINFO		IDD_DIALOG_USERMANAGE+3

#define IDC_BUTTON_USERMANAGE_ADD			IDD_DIALOG_USERMANAGE+4
#define IDC_BUTTON_USERMANAGE_MODIFY		IDD_DIALOG_USERMANAGE+5
#define IDC_BUTTON_USERMANAGE_DEL			IDD_DIALOG_USERMANAGE+6

#define IDC_BUTTON_USERMANAGE_BACK			IDD_DIALOG_USERMANAGE+7

BOOL CreateUsermanagePage();
BOOL ShowUsermanagePage();

void OnUsermanageBack(s32 param);

#endif
