#ifndef _YUNTAICONTROLPAGE_H_
#define _YUNTAICONTROLPAGE_H_

#include "ui.h"
#define IDC_STATIC_YUNTAICTL_PRESET		 IDD_DIALOG_YUNTAICTL+1
#define IDD_DIALOG_YUNTAICTLPRESET		 IDD_DIALOG_YUNTAICTL+2


#define IDC_STATIC_YUNTAICTL_MOVE		 IDD_DIALOG_YUNTAICTL+3
#define IDD_DIALOG_YUNTAICTLMOVE		 IDD_DIALOG_YUNTAICTL+4
#define IDC_STATIC_YUNTAICTL_ZOOM		 IDD_DIALOG_YUNTAICTL+5
#define IDD_DIALOG_YUNTAICTLZOOM		 IDD_DIALOG_YUNTAICTL+6

#define IDC_STATIC_YUNTAICTL_IRIS		 IDD_DIALOG_YUNTAICTL+7
#define IDD_DIALOG_YUNTAICTLIRIS		 IDD_DIALOG_YUNTAICTL+8
#define IDC_STATIC_YUNTAICTL_FOCUS		 IDD_DIALOG_YUNTAICTL+9
#define IDD_DIALOG_YUNTAICTLFOCUS		 IDD_DIALOG_YUNTAICTL+10

#define IDC_STATIC_YUNTAICTL_CRUISE		 IDD_DIALOG_YUNTAICTL+11
#define IDD_DIALOG_YUNTAICTLCRUISE		 IDD_DIALOG_YUNTAICTL+12
#define IDC_STATIC_YUNTAICTL_LIGHT		 IDD_DIALOG_YUNTAICTL+13
#define IDD_DIALOG_YUNTAICTLLIGHT		 IDD_DIALOG_YUNTAICTL+14

#define IDC_STATIC_YUNTAICTL_WIPER		 IDD_DIALOG_YUNTAICTL+17
#define IDD_DIALOG_YUNTAICTLWIPER		 IDD_DIALOG_YUNTAICTL+18
#define IDC_STATIC_YUNTAICTL_AUX		 IDD_DIALOG_YUNTAICTL+19
#define IDD_DIALOG_YUNTAICTLAUX			 IDD_DIALOG_YUNTAICTL+20
#define IDC_STATIC_YUNTAICTL_CT		 IDD_DIALOG_YUNTAICTL+21
#define IDD_DIALOG_YUNTAICTLCT			 IDD_DIALOG_YUNTAICTL+22
#define IDC_STATIC_YUNTAICTL_CT1		 IDD_DIALOG_YUNTAICTL+23
//comment by lshu 20070410
#define IDC_STATIC_YUNTAICTL_CRUISE1		 IDD_DIALOG_YUNTAICTL+24
#define IDC_STATIC_YUNTAICTL_CRUISE2		 IDD_DIALOG_YUNTAICTL+25
//comment end


BOOL CreateYunTaiControlMovePage();
BOOL ShowYunTaiControlMovePage();

BOOL CreateYunTaiControlZoomPage();
BOOL ShowYunTaiControlZoomPage();

BOOL CreateYunTaiControlFocusPage();
BOOL ShowYunTaiControlFocusPage();

BOOL CreateYunTaiControlIrisPage();
BOOL ShowYunTaiControlIrisPage();

BOOL CreateYunTaiControlPresetPage();
BOOL ShowYunTaiControlPresetPage();

BOOL CreateYunTaiControlLightPage();
BOOL ShowYunTaiControlLightPage();

BOOL CreateYunTaiControlWiperPage();
BOOL ShowYunTaiControlWiperPage();

BOOL CreateYunTaiControlCruisePage();
BOOL ShowYunTaiControlCruisePage();

BOOL CreateYunTaiControlAuxPage();
BOOL ShowYunTaiControlAuxPage();
BOOL CreateYunTaiControlCtPage();
BOOL ShowYunTaiControlCtPage();


#endif
