//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MfcDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MFCDEMO_DIALOG              102
#define IDR_MAINFRAME                   128
#define IDC_ServerAddr                  1000
#define IDC_UserID                      1001
#define IDC_UserPW                      1002
#define IDC_ServerModel                 1003
#define IDC_BTlogin                     1004
#define IDC_BTlogout                    1005
#define IDC_PLAYWND1                    1006
#define IDC_PLAYWND2                    1007
#define IDC_PLAYWND3                    1008
#define IDC_PLAYWND4                    1009
#define IDC_PlayAll                     1010
#define IDC_StopAll                     1011
#define IDC_PlayAudio                   1012
#define IDC_StopAudio                   1013
#define IDC_StartRec                    1014
#define IDC_StopRec                     1015
#define IDC_Snap                        1016
#define IDC_COMBOVideoType              1017
#define IDC_Mute                        1018
#define IDC_StartVoip                   1019
#define IDC_StopVoip                    1020
#define IDC_PtzParam                    1021
#define IDC_PLAYWND5                    1022
#define IDC_RecSearch                   1024
#define IDC_SearchClean                 1025
#define IDC_SLIDER1                     1026
#define IDC_FilePlay                    1027
#define IDC_TimePlay                    1028
#define IDC_DownLoad                    1029
#define IDC_PbPause                     1030
#define IDC_PbResume                    1031
#define IDC_PbStep                      1032
#define IDC_PbFast                      1033
#define IDC_PbSlow                      1034
#define IDC_PbRate                      1035
#define IDC_PbPrev                      1036
#define IDC_PbNext                      1037
#define IDC_PbSeek                      1038
#define IDC_PbMute                      1039
#define IDC_PtzCtr                      1040
#define IDC_PtzStop                     1041
#define IDC_SetPreset                   1042
#define IDC_GoPreset                    1043
#define IDC_ClearPreset                 1044
#define IDC_StartRecTrack               1045
#define IDC_StopRecTrack                1046
#define IDC_StartTrack                  1047
#define IDC_StopTrack                   1048
#define IDC_InsertCruise                1049
#define IDC_DeleteCruise                1050
#define IDC_StartCruise                 1051
#define IDC_StopCruise                  1052
#define IDC_ParamSys                    1053
#define IDC_ParamVideo                  1054
#define IDC_ParamRec                    1055
#define IDC_ParamRecTime                1056
#define IDC_ParamException              1057
#define IDC_ParamNetwork                1058
#define IDC_ParamVideoLost              1059
#define IDC_ParamSHTime                 1060
#define IDC_ManualRec                   1061
#define IDC_SysTime                     1062
#define IDC_HddInfo                     1063
#define IDC_SysInfo                     1064
#define IDC_Update                      1065
#define IDC_Restore                     1066
#define IDC_Reboot                      1067
#define IDC_ShutDown                    1068
#define IDC_MDParam                     1069
#define IDC_MDTime                      1070
#define IDC_MDAlarm                     1071
#define IDC_AlarmInParam                1072
#define IDC_AlarmInTime                 1073
#define IDC_AlarmInAlarm                1074
#define IDC_AlarmInPtz                  1075
#define IDC_AlarmOutParam               1076
#define IDC_AlarmOutTime                1077
#define IDC_ClearAlarms                 1078
#define IDC_AlarmState                  1079
#define IDC_LOGSEARCH                   1080
#define IDC_LOGCLEAN                    1081
#define IDC_GetUserList                 1082
#define IDC_AddUser                     1083
#define IDC_DelUser                     1084
#define IDC_ClearUserList               1085
#define IDC_EditUser                    1086
#define IDC_RegConnLost                 1087
#define IDC_GetConnTime                 1088
#define IDC_SetConnTime                 1089
#define IDC_SDKcheck                    1092
#define IDC_ServerPort                  1093
#define IDC_RegAlarmUpload              1094
#define IDC_GetFileFrame                1095
#define IDC_SERIALPORT                  1096
#define IDC_SerialParam                 1097
#define IDC_SerialOpen                  1098
#define IDC_SerialClose                 1099
#define IDC_SETRECONN                   1100
#define IDC_BUTTON_PLONE                1101
#define IDC_BUTTON_POLLING              1102
#define IDC_BUTTON_TIMEDOWNLOAD         1103
#define IDC_testLAS                     1104

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
